from __future__ import annotations

import json
from copy import deepcopy

import pytest

from app.choreography import ChoreographyPlan
from app.models import AssetActivation, CompositionBeat, LayoutItem, StoryBeat
from app.motion import MotionPlanner
from app.motion.timing import MotionTimingPolicy
from app.render.motion import FFmpegMotionAdapter
from app.story.sync_qa import StorySyncQA
from app.story.windows import StoryAssetActivation


def activation(asset_id="a", policy="OWN_WINDOW", reveal=4.8, spoken=5.0, settle=5.7):
    return StoryAssetActivation(
        asset_id=asset_id, spoken_start=spoken, spoken_end=settle,
        trigger_text="spoken meaning", phrase_start=spoken, phrase_end=settle,
        reveal_start=reveal, semantic_peak=(spoken + settle) / 2, settle_at=settle,
        policy="GROUP" if policy == "INHERITED_WINDOW" else "SEMANTIC",
        activation_policy=policy, confidence=0.94, source="test",
    )


def plan(*rows, end=8.0, choreography=None):
    beat = StoryBeat(
        id="b", scene_id="s", start=4, end=end, audio_start=4.2, audio_end=end,
        narration="a scene with several spoken meanings", action="INTRODUCE",
        primary_asset_ids=["a"], asset_activations=list(rows),
    )
    layout = CompositionBeat(beat_id="b", items=[
        LayoutItem(asset_id=row.asset_id, x=0.5, y=0.5, width=0.3, height=0.3, z=i)
        for i, row in enumerate(rows)
    ])
    return beat, MotionPlanner().plan([beat], [layout], choreography)


def actual_settle(cue):
    return cue.start + max(0.05, cue.end - cue.start) * cue.params["program"]["settle_progress"]


def actual_peak(cue):
    peak = max(
        cue.params["program"]["keyframes"],
        key=lambda frame: (
            max(0.0, frame["scale"] - 1.0),
            abs(frame["dx"]) + abs(frame["dy"]),
            frame["progress"],
        ),
    )
    return cue.start + max(0.05, cue.end - cue.start) * peak["progress"]


def evaluate(expression, time):
    # Evaluate only expressions generated by the renderer for this synthetic test.
    return eval(expression.replace("if(", "choose("), {"__builtins__": {}}, {
        "t": time, "choose": lambda c, a, b: a if c else b,
        "lt": lambda a, b: a < b, "gte": lambda a, b: a >= b, "pow": pow,
    })


@pytest.mark.parametrize("choreographed", [False, True])
def test_v2_actual_visual_settle_57_instead_of_spoken_50(choreographed):
    # An empty plan exercises the modern style path; None exercises legacy callers.
    choreography = ChoreographyPlan() if choreographed else None
    row = activation()
    beat, cues = plan(row, choreography=choreography)
    cue = cues[0]
    assert cue.start == pytest.approx(4.8)
    assert cue.params["semantic_settle_time"] == pytest.approx(5.7)
    assert actual_settle(cue) == pytest.approx(5.7)
    adapter = FFmpegMotionAdapter()
    x, y = adapter.position_expressions(
        cue=cue, target_x=100, target_y=120, canvas_width=1000, canvas_height=600,
        segment_start=4, segment_duration=4,
    )
    scale = adapter.scale_expression(cue=cue, segment_start=4, segment_duration=4)
    assert any(abs(value - target) > 1e-8 for value, target in (
        (evaluate(x, 1.65), 100), (evaluate(y, 1.65), 120), (evaluate(scale, 1.65), 1),
    ))
    for time in (1.7, 2, 3.9):
        assert evaluate(x, time) == pytest.approx(100)
        assert evaluate(y, time) == pytest.approx(120)
        assert evaluate(scale, time) == pytest.approx(1)
    assert StorySyncQA().inspect(story=[beat], motion=cues).passed


def test_v2_compiler_remaps_strongest_gesture_to_story_semantic_peak():
    row = activation()
    beat, cues = plan(row, choreography=ChoreographyPlan())
    cue = cues[0]

    assert actual_peak(cue) == pytest.approx(row.semantic_peak, abs=1e-6)
    assert cue.start == pytest.approx(row.reveal_start)
    assert actual_settle(cue) == pytest.approx(row.settle_at)
    settled = [
        frame for frame in cue.params["program"]["keyframes"]
        if frame["progress"] >= cue.params["program"]["settle_progress"]
    ]
    assert all(
        frame["dx"] == 0.0 and frame["dy"] == 0.0 and frame["scale"] == 1.0
        for frame in settled
    )
    assert StorySyncQA().inspect(story=[beat], motion=cues).passed


@pytest.mark.parametrize("reveal,spoken,settle,end", [
    (4.8, 4.805, 4.81, 8), (4.0, 4.001, 4.002, 8),
    (7.8, 7.85, 8, 8), (4, 4.1, 4.5, 8), (7.98, 7.99, 7.995, 8),
])
def test_short_and_boundary_windows_preserve_actual_renderer_timing(reveal, spoken, settle, end):
    beat, cues = plan(activation(reveal=reveal, spoken=spoken, settle=settle), end=end)
    cue = cues[0]
    assert cue.start == pytest.approx(reveal)
    assert actual_settle(cue) == pytest.approx(settle)
    adapter = FFmpegMotionAdapter()
    expressions = adapter.position_expressions(
        cue=cue, target_x=100, target_y=120, canvas_width=1000, canvas_height=600,
        segment_start=beat.start, segment_duration=beat.end - beat.start,
    )
    assert evaluate(expressions[0], settle - beat.start) == pytest.approx(100)
    assert evaluate(expressions[1], settle - beat.start) == pytest.approx(120)
    assert StorySyncQA().inspect(story=[beat], motion=cues).passed


def test_inherited_window_has_no_independent_stagger():
    rows = [activation(), activation("child", "INHERITED_WINDOW"),
            activation("later", reveal=6, spoken=6.2, settle=6.7)]
    beat, cues = plan(*rows)
    assert cues[0].start == cues[1].start == 4.8
    assert actual_settle(cues[0]) == actual_settle(cues[1]) == 5.7
    assert cues[2].start == 6
    assert actual_settle(cues[2]) == 6.7
    assert StorySyncQA().inspect(story=[beat], motion=cues).passed


def test_legacy_target_and_qa_remain_spoken_start():
    row = AssetActivation(asset_id="a", spoken_start=5, spoken_end=5.7,
                          policy="SEMANTIC", confidence=0.94)
    beat, cues = plan(row)
    assert cues[0].params["semantic_settle_time"] == 5
    assert actual_settle(cues[0]) == pytest.approx(5)
    report = StorySyncQA().inspect(story=[beat], motion=cues)
    assert report.passed and report.entries[0].settle_target == 5
    assert report.entries[0].activation_policy is None


def test_serialized_story_evidence_consumed():
    row = activation().with_legacy_evidence()
    original, _ = plan(row)
    legacy = StoryBeat.model_validate_json(original.model_dump_json())
    assert not hasattr(legacy.asset_activations[0], "settle_at")
    beat, cues = plan(*legacy.asset_activations)
    assert cues[0].start == 4.8 and actual_settle(cues[0]) == pytest.approx(5.7)
    assert StorySyncQA().inspect(story=[beat], motion=cues).passed


@pytest.mark.parametrize("changes", [
    {"settle_at": None}, {"reveal_start": float("nan")}, {"settle_at": float("inf")},
    {"semantic_peak": None}, {"reveal_start": 6}, {"settle_at": 9, "phrase_end": 9},
    {"activation_policy": "SAFE_ABSTENTION", "reveal_start": None, "settle_at": None,
     "semantic_peak": None, "phrase_start": None, "phrase_end": None},
])
def test_invalid_or_abstaining_v2_does_not_reuse_spoken_anchor(changes):
    row = activation().model_copy(update=changes)
    beat, cues = plan(row)
    _, fallback_cues = plan(AssetActivation(asset_id="a"))
    assert cues == fallback_cues
    report = StorySyncQA().inspect(story=[beat], motion=cues)
    assert report.passed and report.anchored_assets == 0
    assert report.entries[0].settle_target is None


def test_corrupt_serialized_v2_is_conservative():
    row = AssetActivation(asset_id="a", policy="SEMANTIC", spoken_start=5,
                          evidence=["story_activation_v2:{broken"])
    beat, cues = plan(row)
    _, fallback_cues = plan(AssetActivation(asset_id="a"))
    assert cues == fallback_cues
    assert StorySyncQA().inspect(story=[beat], motion=cues).anchored_assets == 0


@pytest.mark.parametrize("metadata_only", [False, True])
def test_qa_rejects_old_settle_even_if_metadata_claims_v2(metadata_only):
    beat, cues = plan(activation())
    wrong = deepcopy(cues[0])
    wrong.end = 5.0
    wrong.params["semantic_settle_time"] = 5.7 if metadata_only else 5.0
    report = StorySyncQA().inspect(story=[beat], motion=[wrong])
    assert not report.passed
    assert report.max_settle_delta_seconds == pytest.approx(0.7)


def test_qa_diagnostics_include_story_contract_and_actual_settle(tmp_path):
    beat, cues = plan(activation())
    report = StorySyncQA().inspect(story=[beat], motion=cues)
    assert report.passed
    path = tmp_path / "sync.json"
    StorySyncQA.write(report, path)
    entry = json.loads(path.read_text())["entries"][0]
    assert entry["activation_policy"] == "OWN_WINDOW"
    assert entry["spoken_start"] == 5
    assert entry["reveal_start"] == 4.8
    assert entry["semantic_peak"] == 5.35
    assert entry["settle_target"] == entry["motion_settle"] == entry["actual_visual_settle"] == 5.7


def test_early_completion_evidence_does_not_change_motion():
    row = activation()
    _, original = plan(row)
    row.evidence.append("EARLY_SCENE_COMPLETION")
    _, flagged = plan(row)
    assert flagged == original


def test_timing_ignores_asset_index_and_preferred_duration_for_v2():
    row = activation()
    beat, _ = plan(row)
    policy = MotionTimingPolicy()
    for method in (policy.window, policy.legacy_window):
        for index in (0, 4, 19):
            window = method(beat=beat, distance=0.1, index=index, count=20,
                            primary=index == 0, activation=row, settle_progress=0.78)
            assert window.start == 4.8 and window.end == window.semantic_settle == 5.7


def test_qa_rejects_early_final_keyframe_despite_matching_metadata():
    beat, cues = plan(activation())
    cue = deepcopy(cues[0])
    frames = cue.params["program"]["keyframes"]
    previous = float(frames[-2]["progress"])
    final = float(frames[-1]["progress"])
    early_progress = previous + (final - previous) * 0.5
    frames.insert(-1, {**frames[-1], "progress": early_progress})
    report = StorySyncQA().inspect(story=[beat], motion=[cue])
    assert not report.passed
    expected = cue.start + max(0.05, cue.end - cue.start) * early_progress
    assert report.entries[0].actual_visual_settle == pytest.approx(expected)


@pytest.mark.parametrize("damage", ["missing_program", "nonfinite_metadata", "wrong_reveal"])
def test_qa_rejects_missing_actual_evidence_and_invalid_timing(damage):
    beat, cues = plan(activation())
    cue = deepcopy(cues[0])
    if damage == "missing_program":
        del cue.params["program"]
    elif damage == "nonfinite_metadata":
        cue.params["semantic_settle_time"] = float("nan")
    else:
        cue.start += 0.10
    assert not StorySyncQA().inspect(story=[beat], motion=[cue]).passed


def test_final_package_binding_motion_runs_from_phrase_start_to_phrase_end():
    row = activation(reveal=5.0, spoken=5.0, settle=5.7).model_copy(
        update={"source": "final_package_semantic_binding"}
    )
    beat, cues = plan(row)
    cue = cues[0]

    assert cue.start == pytest.approx(5.0)
    assert cue.params["semantic_settle_time"] == pytest.approx(5.7)
    assert actual_settle(cue) == pytest.approx(5.7)
    assert StorySyncQA().inspect(story=[beat], motion=cues).passed
